name: Build extension and upload to blob

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**.ts"
      - "*.json"
      - "rollup.config.mjs"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        lfs: true
    
    - name: Node setup for extension build
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Build extension
      run: |
        mkdir -p ./dist
        npm install
        npm run build

    - name: Produce build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist

    - name: Setup rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: |
          [minio]
          type = s3
          provider = Minio
          env_auth = false
          access_key_id = ${{ secrets.MINIO_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.MINIO_SECRET_ACCESS_KEY }}
          endpoint = cdn.place.heeler.house
          region = us-east-1
        disable_base64: true

    - name: Upload to blob storage
      run: |
        rclone -c copy ./dist "minio:scripts"
